var headerStr = '';
var controlStr = '';
var learningMapStr = '';

controlStr += '<div id="quickBubble"></div>';
controlStr += '<div class="control_wrap">';
controlStr += '    <div class="area_controls1">';
/*controlStr += '        <div class="btn_wrap download">';
controlStr += '            <button id="btn_download"></button>';
controlStr += '            <div class="btn_bubble">학습노트</div>';
controlStr += '        </div>';*/
controlStr += '        <div class="btn_wrap play">';
controlStr += '            <button id="btn_play"></button>';
controlStr += '            <div class="btn_bubble">재생</div>';
controlStr += '        </div>';
controlStr += '        <div class="btn_wrap pause">';
controlStr += '            <button id="btn_pause"></button>';
controlStr += '            <div class="btn_bubble">일시정지</div>';
controlStr += '        </div>';
controlStr += '        <div class="btn_wrap replay">';
controlStr += '            <button id="btn_replay"></button>';
controlStr += '            <div class="btn_bubble">다시보기</div>';
controlStr += '        </div>';
/*controlStr += '        <div class="btn_wrap script">';
controlStr += '            <button id="btn_script"></button>';
controlStr += '            <div class="btn_bubble">자막보기</div>';
controlStr += '        </div>';*/
controlStr += '    </div>';
controlStr += '    <div class="area_bar">';
controlStr += '        <div id="bar_display_bg"><div id="bar_display_mask"><div id="bar_display_fill"></div></div></div>';
controlStr += '        <div id="bar_event"></div>';
controlStr += '        <div id="bar_pointer"></div>';
controlStr += '        <div id="quickMark"></div>';
controlStr += '    </div>';
controlStr += '    <div class="area_time">';
controlStr += '        <div id="cTime">00:00</div>';
controlStr += '        <div id="slice">|</div>';
controlStr += '        <div id="tTime">00:00</div>';
controlStr += '    </div>';
controlStr += '    <div class="area_controls2">';
controlStr += '        <div class="btn_wrap sound">';
controlStr += '            <button id="btn_sound"><span id="sound_mute"></span></button>';
controlStr += '            <div class="btn_bubble">소리 끔</div>';
controlStr += '        </div>';
controlStr += '        <div id="sound_wave">';
controlStr += '            <div id="sound_display_bg"><div id="sound_display_mask"><div id="sound_display_fill"></div></div></div>';
controlStr += '            <div id="sound_event"></div>';
controlStr += '            <div id="sound_pointer"></div>';
controlStr += '        </div>';
/*controlStr += '        <div id="area_speed">';
controlStr += '            <div id="display_speed">×1.0</div>';
controlStr += '            <ul id="speed_list">';
controlStr += '                <li class="btn_speed" data-speed="0.8">×0.8</li>';
controlStr += '                <li class="btn_speed" data-speed="1.0">×1.0</li>';
controlStr += '                <li class="btn_speed" data-speed="1.5">×1.5</li>';
controlStr += '                <li class="btn_speed" data-speed="2.0">×2.0</li>';
controlStr += '            </ul>';
controlStr += '        </div>';*/
controlStr += '    </div>';
controlStr += '    <div class="area_movePage">';
controlStr += '        <div id="btn_prev"></div>';
controlStr += '        <div id="currentPage"></div>';
controlStr += '        <div id="slice"></div>';
controlStr += '        <div id="totalPage"></div>';
controlStr += '        <div id="btn_next"></div>';
controlStr += '    </div>';
controlStr += '    <div id="next_bubble"></div>'
controlStr += '</div>';